### ISSUE TITLE
Erro em todos os endpoints da API

### ISSUE THREAD

**Issue by brenodqestrada** [RioBus/proxy#64]
Realizando qualquer request na API rest do RioBus dá erro 500:

Error: ENOSPC: no space left on device, write
   at Error (native)
   at Object.fs.writeSync (fs.js:706:20)
   at Object.fs.writeFileSync (fs.js:1234:24)
   at Object.fs.appendFileSync (fs.js:1283:6)
   at File.append (/app/src/core/file.js:47:17)
   at Logger.log (/app/src/core/log/logger.js:55:11)
   at Logger.info (/app/src/core/log/logger.js:42:8)
   at /app/src/core/router.js:26:20
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
   at /app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
   at next (/app/node_modules/express/lib/router/index.js:271:10)
   at jsonParser (/app/node_modules/body-parser/lib/types/json.js:100:40)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
   at /app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
   at next (/app/node_modules/express/lib/router/index.js:271:10)
   at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:88:40)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
   at /app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
   at Immediate.next (/app/node_modules/express/lib/router/index.js:271:10)
   at Immediate.immediate._onImmediate (timers.js:435:18)
   at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by fmsouza** [comment]
Oi @brenoqueiros! Obrigado por avisar. O problema já foi resolvido e o sistema está funcionando novamente.
